### ISSUE TITLE
Thank You!

### ISSUE THREAD

**Issue by JeanMichelleJarre** [LemoFire/OpenCore-CUBE-Thinker-i35#1] opened 2020-07-11 11:11 UTC
Hi, thank you for your work! It is an amazing job!
I wanted to ask you a couple of questions if it's not a bother:

1. Is there a way for the trackpad to work? With the version of @titian2019 (Mojave 10.14.6) it did work.
2. Bluetooth doesn't work, right?

Otherwise, with your EFI, 10.15.5 is fantastic. The laptop works amazing! 
Thank you again. Best Regards.

**Comment by UzkiS** [comment] 2020-07-12 16:27
Thank you. This is just an imperfect backup at the moment. At present, Bluetooth is not detected. I tried to use the file of @titian2019 to solve the trackpad problem, but the trackpad device is still not detected like Bluetooth. If the problem is solved one day, I will update it.Thank you for your support(●°u°●)​ 」

**Comment by UzkiS** [comment] 2020-07-12 16:48
It may be a USB problem (@titian2019's version in hackintool, USB will display Bluetooth and trackpad, but they can't be detected in OC. If you have a solution, I hope you can share it with me. Thank you.

**Comment by JeanMichelleJarre** [comment] 2020-07-12 20:13
Sure! If I can make it work, I'll tell you and share you about it here! 
I don't quite understand what you mean about that there must be a USB problem that Clover 10.14.6 did detect trackpad and bluetooth and in OC 10.15.5 it didn't. I don't quite understand that correlation. :_ / 
Thank you anyway. I'm will try to study it. =)

**Comment by UzkiS** [comment] 2020-07-16 12:07
> Sure! If I can make it work, I'll tell you and share you about it here!
> I don't quite understand what you mean about that there must be a USB problem that Clover 10.14.6 did detect trackpad and bluetooth and in OC 10.15.5 it didn't. I don't quite understand that correlation. :_ /
> Thank you anyway. I'm will try to study it. =)

hi. the Bluetooth Camera can fixed by Usbinjectall.kext. but trackpad still doesn't work.

**Comment by JeanMichelleJarre** [comment] 2020-07-16 14:50
> > Sure! If I can make it work, I'll tell you and share you about it here!
> > I don't quite understand what you mean about that there must be a USB problem that Clover 10.14.6 did detect trackpad and bluetooth and in OC 10.15.5 it didn't. I don't quite understand that correlation. :_ /
> > Thank you anyway. I'm will try to study it. =)
> 
> hi. the Bluetooth Camera can fixed by Usbinjectall.kext. but trackpad still doesn't work.

Uuuuh, great!! ^_^/ 
USBinjectall.kext listed of config.plist and running bluetooth!
I have also been testing to make the trackpad work but my knowledge to get it to work does not go that far. I have not managed to make it work. See if you and @titian2019 get it! You are machines. =))

**Comment by JeanMichelleJarre** [comment] 2020-07-17 12:34
Fantastic job, @LemoFire! Thank you so much! 
Installed and tested 10.15.6 and running ok! (also wifi and Bluetooth)

**Comment by UzkiS** [comment] 2020-07-17 17:12
> Fantastic job, @LemoFire! Thank you so much!
> Installed and tested 10.15.6 and running ok! (also wifi and Bluetooth)

OK, have fun: ) , but the problem with the touchpad should be the compatibility between OC and voodoo. I have found many people who can't solve this problem. It's hard

**Closed as completed** 2020-07-18 16:11 UTC
